### ISSUE TITLE
Output: JSON or other?

### ISSUE THREAD

**Issue by jeremyjbowers** [jsfenfen/paper_fec#3]
For example, Postgres's `copy` function wants comma-delimited.

http://initd.org/psycopg/docs/cursor.html#cursor.copy_from

**Comment by jeremyjbowers** [comment]
Might want to run this as a psql system call instead of through `psycopg2` OR load the file as a `StringIO` object and using a generator instead of reading the whole thing into memory?

**Comment by jeremyjbowers** [comment]
StringIO reads 8192 bytes at a time into the generator, so that might be decent. http://blog.endpoint.com/2014/04/speeding-up-saving-millions-of-orm.html

**Comment by jsfenfen** [comment]
There's an implementation of something like this on realtime. Basically it uses csv writer to write the data to a csv; but instead of csv writing to file it writes it to a cstring. Then it uses load_expert to load the data. It's set to commit 1000 rows at a time (and whenever a filing is done whatever is left over is committed). 

There's a bit of weirdness related to delimiters, which I should revisit, but this is pretty effective.

Relevant classes: 

https://github.com/sunlightlabs/read_FEC/blob/master/fecreader/formdata/utils/write_csv_to_db.py
It gets called from here: https://github.com/sunlightlabs/read_FEC/blob/master/fecreader/formdata/utils/filing_body_processor.py#L78

Also this, on skedA, to streamline loading (getting rid of django's default primary key) and setting the fillfactor: https://github.com/sunlightlabs/read_FEC/blob/master/fecreader/formdata/sql/SkedA.sql
