### ISSUE TITLE
Remove dependencies on filesystem.

### ISSUE THREAD

**Issue by jeremyjbowers** [jsfenfen/paper_fec#4]
Can we act directly on the request object instead of writing it to disk? Or do we need some kind of data store?

**Comment by jsfenfen** [comment]
That's doable, I think, but doing it so that it doesn't suck the entire file into memory requires a little work, I think. Here's an example, I think: http://stackoverflow.com/a/10305494 . The downloaded chunks would have to be reassembled into lines such that the parser could be fed one line at a time. There may be a more straightforward approach, I dunno.  

You could also just commit to having enough memory available to process whole files--lemme see if I can dig up the biggest ones I can find. That approach is just a little scary because these files can be arbitrarily large.

**Comment by jeremyjbowers** [comment]
Thinking about this now.

**Comment by jeremyjbowers** [comment]
How big is a "big" file? Gigabytes?

**Comment by jsfenfen** [comment]
Hmm, one of the biggest I can find is 500Mb ( 838168.fec ), not positive
that's the biggest.

A random list I used earlier for testing with some of the bigger 2012
filings.

file_list = [838168, 824988, 840327, 821325, 798883, 804867, 827978, 754317]
